/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BrandVoiceProfile {
  'personality' : string,
  'tone' : string,
  'consistency' : string,
}
export interface ContentGenerationRequest {
  'goal' : string,
  'tone' : string,
  'audience' : string,
  'platform' : string,
  'niche' : string,
}
export interface FeatureSet {
  'roadmap' : boolean,
  'facelessVersion' : boolean,
  'hashtags' : boolean,
  'hooks' : boolean,
  'scripts' : boolean,
  'affiliateSuggestions' : boolean,
  'contentScore' : boolean,
  'calendar' : boolean,
  'captions' : boolean,
  'monetizationAngles' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type SubscriptionStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'pending' : null };
export type TierLevel = { 'pro' : null } |
  { 'free' : null } |
  { 'elite' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSubscription {
  'status' : SubscriptionStatus,
  'tier' : TierLevel,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContentRequest' : ActorMethod<[ContentGenerationRequest], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkUserTier' : ActorMethod<[], FeatureSet>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'generateCalendar' : ActorMethod<[ContentGenerationRequest], string>,
  'generateCaptions' : ActorMethod<[ContentGenerationRequest], Array<string>>,
  'generateHooks' : ActorMethod<[ContentGenerationRequest], Array<string>>,
  'generateScripts' : ActorMethod<[ContentGenerationRequest], Array<string>>,
  'getBrandVoiceProfile' : ActorMethod<[], [] | [BrandVoiceProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContentRequests' : ActorMethod<[], Array<ContentGenerationRequest>>,
  'getMySubscription' : ActorMethod<[], [] | [UserSubscription]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'processSubscriptionUpgrade' : ActorMethod<[Principal, TierLevel], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setBrandVoiceProfile' : ActorMethod<[BrandVoiceProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setUserSubscription' : ActorMethod<
    [Principal, TierLevel, SubscriptionStatus],
    undefined
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];