/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ContentGenerationRequest = IDL.Record({
  'goal' : IDL.Text,
  'tone' : IDL.Text,
  'audience' : IDL.Text,
  'platform' : IDL.Text,
  'niche' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FeatureSet = IDL.Record({
  'roadmap' : IDL.Bool,
  'facelessVersion' : IDL.Bool,
  'hashtags' : IDL.Bool,
  'hooks' : IDL.Bool,
  'scripts' : IDL.Bool,
  'affiliateSuggestions' : IDL.Bool,
  'contentScore' : IDL.Bool,
  'calendar' : IDL.Bool,
  'captions' : IDL.Bool,
  'monetizationAngles' : IDL.Nat,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const TierLevel = IDL.Variant({
  'pro' : IDL.Null,
  'free' : IDL.Null,
  'elite' : IDL.Null,
});
export const BrandVoiceProfile = IDL.Record({
  'personality' : IDL.Text,
  'tone' : IDL.Text,
  'consistency' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
});
export const UserSubscription = IDL.Record({
  'status' : SubscriptionStatus,
  'tier' : TierLevel,
  'customerId' : IDL.Opt(IDL.Text),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const WebhookEventType = IDL.Variant({
  'checkoutSessionCompleted' : IDL.Null,
  'customerSubscriptionUpdated' : IDL.Null,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContentRequest' : IDL.Func([ContentGenerationRequest], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkUserTier' : IDL.Func([], [FeatureSet], ['query']),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createStripeCheckoutSession' : IDL.Func(
      [TierLevel, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'generateCalendar' : IDL.Func([ContentGenerationRequest], [IDL.Text], []),
  'generateCaptions' : IDL.Func(
      [ContentGenerationRequest],
      [IDL.Vec(IDL.Text)],
      [],
    ),
  'generateHooks' : IDL.Func(
      [ContentGenerationRequest],
      [IDL.Vec(IDL.Text)],
      [],
    ),
  'generateScripts' : IDL.Func(
      [ContentGenerationRequest],
      [IDL.Vec(IDL.Text)],
      [],
    ),
  'getBrandVoiceProfile' : IDL.Func(
      [],
      [IDL.Opt(BrandVoiceProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContentRequests' : IDL.Func(
      [],
      [IDL.Vec(ContentGenerationRequest)],
      ['query'],
    ),
  'getMySubscription' : IDL.Func([], [IDL.Opt(UserSubscription)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'processSubscriptionUpgrade' : IDL.Func([IDL.Principal, TierLevel], [], []),
  'processWebhook' : IDL.Func(
      [WebhookEventType, IDL.Text, IDL.Opt(TierLevel), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setBrandVoiceProfile' : IDL.Func([BrandVoiceProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setUserSubscription' : IDL.Func(
      [IDL.Principal, TierLevel, SubscriptionStatus],
      [],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ContentGenerationRequest = IDL.Record({
    'goal' : IDL.Text,
    'tone' : IDL.Text,
    'audience' : IDL.Text,
    'platform' : IDL.Text,
    'niche' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FeatureSet = IDL.Record({
    'roadmap' : IDL.Bool,
    'facelessVersion' : IDL.Bool,
    'hashtags' : IDL.Bool,
    'hooks' : IDL.Bool,
    'scripts' : IDL.Bool,
    'affiliateSuggestions' : IDL.Bool,
    'contentScore' : IDL.Bool,
    'calendar' : IDL.Bool,
    'captions' : IDL.Bool,
    'monetizationAngles' : IDL.Nat,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const TierLevel = IDL.Variant({
    'pro' : IDL.Null,
    'free' : IDL.Null,
    'elite' : IDL.Null,
  });
  const BrandVoiceProfile = IDL.Record({
    'personality' : IDL.Text,
    'tone' : IDL.Text,
    'consistency' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
  });
  const UserSubscription = IDL.Record({
    'status' : SubscriptionStatus,
    'tier' : TierLevel,
    'customerId' : IDL.Opt(IDL.Text),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const WebhookEventType = IDL.Variant({
    'checkoutSessionCompleted' : IDL.Null,
    'customerSubscriptionUpdated' : IDL.Null,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContentRequest' : IDL.Func([ContentGenerationRequest], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkUserTier' : IDL.Func([], [FeatureSet], ['query']),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createStripeCheckoutSession' : IDL.Func(
        [TierLevel, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'generateCalendar' : IDL.Func([ContentGenerationRequest], [IDL.Text], []),
    'generateCaptions' : IDL.Func(
        [ContentGenerationRequest],
        [IDL.Vec(IDL.Text)],
        [],
      ),
    'generateHooks' : IDL.Func(
        [ContentGenerationRequest],
        [IDL.Vec(IDL.Text)],
        [],
      ),
    'generateScripts' : IDL.Func(
        [ContentGenerationRequest],
        [IDL.Vec(IDL.Text)],
        [],
      ),
    'getBrandVoiceProfile' : IDL.Func(
        [],
        [IDL.Opt(BrandVoiceProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContentRequests' : IDL.Func(
        [],
        [IDL.Vec(ContentGenerationRequest)],
        ['query'],
      ),
    'getMySubscription' : IDL.Func([], [IDL.Opt(UserSubscription)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'processSubscriptionUpgrade' : IDL.Func([IDL.Principal, TierLevel], [], []),
    'processWebhook' : IDL.Func(
        [WebhookEventType, IDL.Text, IDL.Opt(TierLevel), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setBrandVoiceProfile' : IDL.Func([BrandVoiceProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setUserSubscription' : IDL.Func(
        [IDL.Principal, TierLevel, SubscriptionStatus],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };